name: local
variables:
  - name: base_url
    value: http://localhost:8000
  - name: article_uuid
    value: ""
  - name: office_id
    value: "1"
  - name: Bearer
    value: 1|GI21EfDgojlN3ymi77hE68Q1QQFgEgv1zj48iXx2dab724c8
