name: local
variables:
  - name: base_url
    value: http://127.0.0.1:8000
  - name: Bearer
    value: Yh56KlYvgggB2V4Va6txzojPIMh2YyvbdYclVl7B9b3a0038
  - name: article_uuid
    value: ""
  - name: office_id
    value: "1"
